version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mindbridge
      POSTGRES_PASSWORD: mindbridge
      POSTGRES_DB: mindbridge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: