#!/bin/bash

echo ""
echo "🔑 ================================"
echo "   Gemini API Key - Quick Guide"
echo "================================"
echo ""
echo "Opening the API key page in your browser..."
echo ""
echo "📋 WHAT TO DO:"
echo ""
echo "1️⃣  You'll see a page with 'Get API Key' button"
echo ""
echo "2️⃣  Click 'Get API Key'"
echo ""
echo "3️⃣  You'll see TWO options:"
echo "    ✅ Create API key in new project"
echo "    ❌ Create API key in existing project"
echo ""
echo "4️⃣  Click '✅ Create API key in new project'"
echo "    (Don't worry about the 'No Cloud Projects' message)"
echo ""
echo "5️⃣  Google creates a project automatically!"
echo ""
echo "6️⃣  Copy the key (looks like: AIzaSyABC123...)"
echo ""
echo "7️⃣  Open .env file in this folder"
echo ""
echo "8️⃣  Replace:"
echo "    GEMINI_API_KEY=AIzaSyDummyKeyPleaseReplaceWithRealOne"
echo ""
echo "9️⃣  With:"
echo "    GEMINI_API_KEY=your_copied_key_here"
echo ""
echo "🔟  Restart: Press Ctrl+C, then run 'npm run dev'"
echo ""
echo "================================"
echo "🎉 Done! Your AI is fully powered!"
echo "================================"
echo ""

# Try to open the URL
open "https://aistudio.google.com/app/apikey" 2>/dev/null || \
xdg-open "https://aistudio.google.com/app/apikey" 2>/dev/null || \
echo "Please manually open: https://aistudio.google.com/app/apikey"

echo ""
echo "💡 TIP: The chatbot WORKS NOW with smart responses!"
echo "    The API key just makes it EVEN BETTER!"
echo ""
