#!/bin/bash

# Visual Checklist for Vercel Environment Variables Setup

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 VERCEL ENVIRONMENT VARIABLES SETUP CHECKLIST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Follow these steps IN ORDER:"
echo ""

echo "☐ STEP 1: Open Vercel Dashboard"
echo "   └─ Click: https://vercel.com/dashboard"
echo ""

echo "☐ STEP 2: Go to Your Project"
echo "   └─ Find and click 'MindBridge' project"
echo ""

echo "☐ STEP 3: Get Database URLs"
echo "   ├─ Click 'Storage' tab (top menu)"
echo "   ├─ Click your Postgres database"
echo "   ├─ Click '.env.local' tab"
echo "   └─ Copy these values:"
echo "      • POSTGRES_PRISMA_URL"
echo "      • POSTGRES_URL_NON_POOLING"
echo ""

echo "☐ STEP 4: Add Environment Variables"
echo "   ├─ Click 'Settings' tab"
echo "   ├─ Click 'Environment Variables' (left sidebar)"
echo "   └─ Add these 4 variables:"
echo ""
echo "      ┌─────────────────────────────────────────┐"
echo "      │ Variable 1                              │"
echo "      ├─────────────────────────────────────────┤"
echo "      │ Name:  mb_PRISMA_DATABASE_URL          │"
echo "      │ Value: [POSTGRES_PRISMA_URL]           │"
echo "      │ Envs:  ✓ Production ✓ Preview ✓ Dev   │"
echo "      └─────────────────────────────────────────┘"
echo ""
echo "      ┌─────────────────────────────────────────┐"
echo "      │ Variable 2                              │"
echo "      ├─────────────────────────────────────────┤"
echo "      │ Name:  mb_POSTGRES_URL                 │"
echo "      │ Value: [POSTGRES_URL_NON_POOLING]      │"
echo "      │ Envs:  ✓ Production ✓ Preview ✓ Dev   │"
echo "      └─────────────────────────────────────────┘"
echo ""
echo "      ┌─────────────────────────────────────────┐"
echo "      │ Variable 3                              │"
echo "      ├─────────────────────────────────────────┤"
echo "      │ Name:  JWT_SECRET                      │"
echo "      │ Value: enigmah                         │"
echo "      │ Envs:  ✓ Production ✓ Preview ✓ Dev   │"
echo "      └─────────────────────────────────────────┘"
echo ""
echo "      ┌─────────────────────────────────────────┐"
echo "      │ Variable 4                              │"
echo "      ├─────────────────────────────────────────┤"
echo "      │ Name:  GEMINI_API_KEY                  │"
echo "      │ Value: AIzaSyAgoRnn8YZHSRv29fdtfegr... │"
echo "      │ Envs:  ✓ Production ✓ Preview ✓ Dev   │"
echo "      └─────────────────────────────────────────┘"
echo ""

echo "☐ STEP 5: Redeploy"
echo "   ├─ Click 'Deployments' tab"
echo "   ├─ Click ⋯ on latest deployment"
echo "   ├─ Click 'Redeploy'"
echo "   └─ Wait 2-3 minutes"
echo ""

echo "☐ STEP 6: Seed Database"
echo "   └─ Run: curl -X POST https://your-app.vercel.app/api/seed"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️  CRITICAL: Don't include quotes around values!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Need help? Read: VERCEL_SETUP_NOW.md"
echo ""
